---
title: "Dead Dogs Analytics - Data Visualization"
author: "Alessandro Speranza"
date: "12/30/2020"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cash = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(googlesheets4)
library(funModeling)
library(here)
library(hrbrthemes)
library(ggtext)
library(bbplot)
```

## Load Data from Google Sheets
```{r message=FALSE, warning=FALSE}

table_data <- read_sheet("https://docs.google.com/spreadsheets/d/1EFikbvCVYHvqC2ExJBOcVKHsA7dRC111OBRxlIH-_R4/edit#gid=724152393", sheet = "Table data") %>% 
  janitor::clean_names()

chart_data <- read_sheet("https://docs.google.com/spreadsheets/d/1EFikbvCVYHvqC2ExJBOcVKHsA7dRC111OBRxlIH-_R4/edit#gid=48952002", sheet = "Chart data") %>% 
  janitor::clean_names()

totals <- read_sheet("https://docs.google.com/spreadsheets/d/1EFikbvCVYHvqC2ExJBOcVKHsA7dRC111OBRxlIH-_R4/edit#gid=1225572154", sheet = "Totals") %>% 
  janitor::clean_names()
```

## Alternative solution - Load Data from csv files
```{r message=FALSE, warning=FALSE}
here::here()

table_data <- read_csv(here("T&DV - by projects", "Dead Dogs Analytics", "data", "20201231", "Table data.csv")) %>% 
  janitor::clean_names()

chart_data <- read_csv(here("T&DV - by projects", "Dead Dogs Analytics", "data", "20201231", "Chart data.csv")) %>% 
  janitor::clean_names()

totals <- read_csv(here("T&DV - by projects", "Dead Dogs Analytics", "data", "20201231", "Totals.csv")) %>% 
  janitor::clean_names()
```

## EDA
```{r}
glimpse(table_data)
df_status(table_data)
```

## Data Preparation (original)
```{r}
table_data_rank <- table_data %>%
  dplyr::filter(!is.na(video_title)) %>%
  dplyr::select(video_title, views) %>%
  tidyr::separate(video_title, sep = "-", into = c("song", "concert"), remove = FALSE) %>%
  mutate(song = str_trim(song), 
         concert = stringr::str_trim(concert),
         video_title_plot = str_c(song, concert, sep = "\n")) %>%
  dplyr::relocate(video_title_plot, .before = views) %>%  #relocate video_title_plot before views
  dplyr::slice_max(order_by = views, n = 10)
```

## Data Visualization
```{r, message=FALSE}
rank <- ggplot(table_data_rank, aes(x = reorder(video_title, views), y = views)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  theme_classic(base_size = 17) +
  labs(x = '', 
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Data from Dead Dogs Youtube Channel")

ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank1.png"), width=16, dpi=300)
```

```{r, message=FALSE}
rank <- ggplot(table_data_rank, aes(x = reorder(video_title, views), y = views)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = views)) +
  coord_flip() +
  theme_ipsum() +
  scale_color_ipsum() +
  labs(x = '', 
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Data: Dead Dogs Youtube Channel")

ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank2.png"), width=16, dpi=300)
```

```{r, message=FALSE}
rank <- ggplot(table_data_rank, aes(x = reorder(video_title, views), y = views)) +
  geom_bar(stat = "identity", fill = "#1380A1") +
  geom_text(aes(label = views), size = 4) +
  coord_flip() +
  theme_ipsum_rc() +
  scale_color_ipsum() +
  labs(x = '', 
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Source: Dead Dogs YouTube Channel")
  theme_ipsum_rc(grid="XY") # rallenta tutto

ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank3.png"), width=15, dpi=300)
```

```{r, message=FALSE}
rank <- ggplot(table_data_rank, aes(x = reorder(video_title, views), y = views)) +
  geom_bar(stat = "identity", fill = "#1380A1") +
  geom_text(aes(label = views), size = 4, hjust = 1.1, color="white") +
  coord_flip() +
  # theme_ipsum_rc() +
  # scale_color_ipsum() +
  labs(x = '', 
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Source: Dead Dogs YouTube Channel")

ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank4.png"), width=15, dpi=300)
```

```{r plot}
ggplot(table_data_rank, aes(x = reorder(video_title_plot, views), y = views)) +
  geom_bar(stat = "identity", fill = "#1380A1") +
  geom_text(aes(label = views), size = 4, hjust = 1.1, color="white", fontface = "bold") +
  coord_flip() +
  theme_classic(base_size = 17) +
  # theme_ipsum() +
  # scale_color_ipsum() +
  theme(axis.text.y = element_text(size = 12, face = "bold")) +
  labs(x = '',
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Source: Dead Dogs YouTube Channel")

# ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank5.png"), width=15, dpi=300)

# USARE il tool per esportare le immagini di tidytuesday
```

```{r}
table_data_rank2 <- table_data_rank %>% 
  mutate(color = "#009E73",
         name = glue("<i style='color:{color}'>{song}</i> ({concert})"))

rank <- ggplot(table_data_rank, aes(x = reorder(video_title_plot, views), y = views)) +
  geom_bar(stat = "identity", fill = "#1380A1") +
  geom_text(aes(label = views), size = 4, hjust = 1.1, color="white") +
  coord_flip() +
  # theme_ipsum_rc() +
  # scale_color_ipsum() +
  scale_x_discrete(
    labels = function(x) {"<i style='color:#0000FF'>", x, "</i>"}
  ) +
  theme(axis.text.x = element_markdown())
  # theme(axis.text.y = element_text(size = 10, face = "bold"))
  # theme(axis.text.y = element_markdown())

# plot.title.position = "plot"
# plot.subtitle,
#   plot.caption,
#   plot.caption.position,

  # labs(x = '', 
  #      y = "Views",
  #      title = "Dead Dogs Songs - Top 10",
  #      subtitle = "27/07/2016 - 31/12/2020",
  #      caption = "Source: Dead Dogs YouTube Channel")

rank

# ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank6.png"), width=15, dpi=300)
```

## BBC version
```{r, message=FALSE}
rank <- ggplot(table_data_rank, aes(x = reorder(video_title, views), y = views)) +
  geom_bar(stat = "identity", fill = "#1380A1") +
  geom_text(aes(label = views), position = position_dodge(width=0.9),  size=10) +
  # geom_hline(yintercept = 0, size = 1, colour="#333333") +
  coord_flip() +
  bbc_style() +
  labs(x = '', 
       y = "Views",
       title = "Dead Dogs Songs - Top 10",
       subtitle = "27/07/2016 - 31/12/2020",
       caption = "Data: Dead Dogs YouTube Channel")

# finalise_plot(plot_name = rank,
#               source = "Source: Dead Dogs YouTube Channel",
#               save_filepath = "C:/Users/asperanz/Downloads/rank4b.png",
#               width_pixels = 1600,
#               height_pixels = 750)
              # logo_image_path = "C:/Users/asperanz/Downloads/Dead Dogs Logos/Dead Dogs Logo.png")

ggsave(here("T&DV - by projects", "Dead Dogs Analytics", "output", "rank4.png"), width=15, dpi=300)
```

