---
title: "Calling YouTube Data API Combined - Dead Dogs Analytics EU Project"
author: "Alessandro Speranza"
date: "01/20/2021"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cash = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly) # BE CAREFUL!! load plotly pkg before httr pkg
library(janitor)
library(jsonlite)
library(httr)
library(here)
```

# Google Authentication
```{r}
endpoints <- oauth_endpoints("google")

# IMPORTANT! Connect to Google with Gino Latino account
myapp <- oauth_app("dead-dogs-analytics-eu-312016",
                   key = "1052109616055-lst9q3ru7ar16800ac62jiv8drs7abvg.apps.googleusercontent.com",
                   secret = "ndKgxUCrZ8BBgT4lEeD6V3CN")

access_token <- oauth2.0_token(endpoints, myapp, scope = "https://www.googleapis.com/auth/yt-analytics.readonly")
```

```{r}
# Highway to Hell
request <- "https://youtubeanalytics.googleapis.com/v2/reports?dimensions=day,video&metrics=views&filters=video==Wq3fJVYb8Qw&maxResults=500&sort=-day&startDate=2021-01-01&endDate=2021-12-31&ids=channel==MINE"

request <- "https://youtubeanalytics.googleapis.com/v2/reports?dimensions=video&metrics=estimatedMinutesWatched,views,likes,subscribersGained&maxResults=10&sort=-estimatedMinutesWatched&startDate=2021-01-01&endDate=2021-12-31&maxResults=200&ids=channel==MINE"

req_youtube <- GET(request, config(token = access_token))

youtube_text <- content(req_youtube, "text", encoding="UTF-8")

youtube_json <- fromJSON(youtube_text, flatten = TRUE)

df <- as.data.frame(youtube_json[["rows"]]) #%>% 
  # arrange(V1) %>% 
  # rename(date = V1,
  #        items_snippet_resource_id_video_id = V2,
  #        views = V3) %>% 
  # mutate(views = as.numeric(views))
```


# get_channel info using YouTube Data API
```{r}
api_call_channel <- "https://www.googleapis.com/youtube/v3/channels?key=AIzaSyDnnrylz50HrA6Ojfog6Lj8aIex1E_j-f0&id=UCBfhv39Ds0JxIODN_iUmL4w&part=snippet,contentDetails,statistics&maxResults=15"

api_result_channel <- httr::GET(api_call_channel)

json_result_channel <- httr::content(api_result_channel, "text", encoding="UTF-8")

# Process the raw data into a data frame
json_channel <- fromJSON(json_result_channel, flatten = T)

channels <- as.data.frame(json_channel) %>% 
   janitor::clean_names()
```

# get_playlists info using YouTube Data API
```{r}
api_call_playlists <- "https://www.googleapis.com/youtube/v3/playlists?key=AIzaSyDnnrylz50HrA6Ojfog6Lj8aIex1E_j-f0&channelId=UCBfhv39Ds0JxIODN_iUmL4w&part=snippet,contentDetails,player,status&maxResults=15"

api_result_playlists <- httr::GET(api_call_playlists)

json_result_playlists <- httr::content(api_result_playlists, "text", encoding="UTF-8")

# Process the raw data into a data frame
json_playlists <- fromJSON(json_result_playlists, flatten = T)

playlists <- as.data.frame(json_playlists) %>% 
   janitor::clean_names()
```

# get_playlistItems info using YouTube Data API
```{r}
api_call_playlistItems <- "https://www.googleapis.com/youtube/v3/playlistItems?key=AIzaSyDnnrylz50HrA6Ojfog6Lj8aIex1E_j-f0&playlistId=PLpfzS9yh-gQZ-giBBdPIxK72fek5dkRE6&part=snippet,status&maxResults=50"

api_result_playlistItems <- httr::GET(api_call_playlistItems)

json_result_playlistItems <- httr::content(api_result_playlistItems, "text", encoding="UTF-8")

# Process the raw data into a data frame
json_playlistItems <- fromJSON(json_result_playlistItems, flatten = T)

playlistItems <- as.data.frame(json_playlistItems) %>% 
   janitor::clean_names()
```

# get_videos info using YouTube Data API
```{r}
api_call_videos <- "https://www.googleapis.com/youtube/v3/videos?key=AIzaSyDnnrylz50HrA6Ojfog6Lj8aIex1E_j-f0&id=Wq3fJVYb8Qw&part=statistics&maxResults=50"

api_result_videos <- httr::GET(api_call_videos)

json_result_videos <- httr::content(api_result_videos, "text", encoding="UTF-8")

# Process the raw data into a data frame
json_videos <- fromJSON(json_result_videos, flatten = T)

videos <- as.data.frame(json_videos) %>% 
   janitor::clean_names()
```





# Merge info
```{r}
videos_final <- inner_join(df, playlistItems, by = "items_snippet_resource_id_video_id") %>%
  select(date, items_snippet_title, views) %>% 
  mutate(date = as.Date(date),
         views = as.integer(views))

glimpse(videos_final)
```

# Plotting the views history
```{r}
ggplotly(ggplot(videos_final, aes(x = date, y = views)) +
  geom_line(color = "dark green"))
```

# Plotting the views history - highcharter
```{r}
library(highcharter)

hchart(videos_final, "line", hcaes(x = date, y = views))

videos_ts <- xts(videos_final, order.by = videos_final$date)

hchart(videos_ts, type = "line", color = "green")  # non va, vedere perche' --->>> MOLTO BELLO
```

# Plotting the views history - dygraphs

```{r}
library(xts)
library(dygraphs)

videos_ts <- xts(videos_final, order.by = videos_final$date)

dygraph(videos_ts, main = "Whole Lotta Shakin' Goin' On Views") %>% 
  dyRangeSelector(height = 20, strokeColor = "") %>% 
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set2"))

dygraph(videos_ts, main = "Whole Lotta Shakin' Goin' On Views") %>% 
  dyRangeSelector(height = 20, strokeColor = "") %>% 
  dyOptions(fillGraph = TRUE, fillAlpha = 0.4)

dygraph(videos_ts, main = "Whole Lotta Shakin' Goin' On Views") %>% 
  dyRangeSelector(height = 20, strokeColor = "") %>% 
dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE)

dygraph(videos_ts, main = "Whole Lotta Shakin' Goin' On Views") %>% 
  dyRangeSelector(height = 20, strokeColor = "") %>% 
dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))
```



